INSERT INTO RENTER(ID, NAME) VALUES (1, 'RENTER1');
INSERT INTO RENTER(ID, NAME) VALUES (2, 'RENTER2');
INSERT INTO RENTER(ID, NAME) VALUES (3, 'RENTER3');

INSERT INTO OBJECT_FOR_RENT(ID, NAME, PRICE, AREA, DESCRIPTION) VALUES (1, 'NAME1', 100.0, 'AREA1', 'DESCRIPTION1');
INSERT INTO OBJECT_FOR_RENT(ID, NAME, PRICE, AREA, DESCRIPTION) VALUES (2, 'NAME2', 200.0, 'AREA2', 'DESCRIPTION2');
INSERT INTO OBJECT_FOR_RENT(ID, NAME, PRICE, AREA, DESCRIPTION) VALUES (3, 'NAME3', 300.0, 'AREA3', 'DESCRIPTION3');
INSERT INTO OBJECT_FOR_RENT(ID, NAME, PRICE, AREA, DESCRIPTION) VALUES (4, 'NAME4', 400.0, 'AREA4', 'DESCRIPTION4');